/*
 * Auto-generated ESP32 code
 * Generated by Atech Hardware Platform
 * Using athera module drivers with FreeRTOS tasks
 */

// ========== INCLUDES ==========
#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_task_wdt.h"
#include "esp_system.h"
#include <Preferences.h>
#include "modules/shared/atech_helpers.h"
#include "modules/shared/atech_ui.h"
#include "modules/connectivity/serial_templates.h"
#include "modules/audio/speaker.h"
#include "modules/display/st7735_tft.h"
#include "modules/input/rotary_encoder.h"
#include "modules/input/button.h"
// EMBEDDED_SOUNDS_FP: none
#include <ArduinoJson.h>

// ========== FREERTOS TASK HANDLES ==========
TaskHandle_t mainTaskHandle = NULL;

// ========== GLOBAL VARIABLES ==========
// ========== USB-SERIAL TRANSPORT ==========
AtechSerial wifi(115200);

// ========== MODULE INSTANCES ==========
// I2S Speaker (MAX98357A)
// Pins swapped for left-side placement: port_6 pins first, port_5 pins second
Speaker speaker_1(12, 13, 10);
// ST7735 TFT Color Display (160x80)
ST7735_TFT st7735_tft_1(2, 41, 1, 40);
// Rotary Encoder Knob
// Pins swapped for left-side placement: port_2 pins first, port_1 pins second
RotaryEncoder rotary_encoder_1(5, 4, 9, 8);
// Button
ButtonModule button_1(17, true);
// Button
ButtonModule button_2(16, true);


// User behavior variables and helper functions
#include <Fonts/FreeSansBold9pt7b.h>
#include <Fonts/FreeSansBold18pt7b.h>
#include <Fonts/FreeSans9pt7b.h>
#define UI_BG     ST7735_TFT::COLOR_BLACK
#define UI_LABEL  ST7735_TFT::COLOR_WHITE
#define UI_VALUE  ST7735_TFT::COLOR_CYAN
#define UI_ACCENT ST7735_TFT::COLOR_ORANGE
// SID: real waveforms for button 2 / set_waveform (index -> SID control bits, see sidWaveBits)
const char* WAVE_NAMES[4] = {"TRIANGLE", "SAW", "PULSE", "NOISE"};
const int NOTE_TABLE[12] = {NOTE_C4, NOTE_D4, NOTE_E4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_F5, NOTE_G5};
const char* NOTE_NAMES[12] = {"C", "D", "E", "F", "G", "A", "B", "C+", "D+", "E+", "F+", "G+"};
int noteIndex = 0;      // 0-11, driven by encoder
int octave = 4;         // 3-6
int waveform = 0;       // 0=triangle 1=sawtooth 2=pulse (pulseWidth %) 3=noise — applied to voice 0
int pulseWidth = 45;    // duty cycle percent for the pulse oscillator
bool noteHeld = false;
unsigned long lastNoteTriggerMs = 0;
unsigned long lastFrameMs = 0;
bool needsRedraw = true;
int32_t lastEncoderPos = 0;
int lastVoice = 0;
struct SidVoice {
  float freq;
  int waveform;
  int pulseWidth;
  uint32_t acc;
  float phase;
  bool gated;
  int stage;      // 0=idle 1=attack 2=decay 3=sustain 4=release
  float env;
  float smooth;
  long remaining;
};
SidVoice sidVoices[3] = {
  {440.0f, 0, 50, 0, 0.0f, false, 0, 0.0f, 0.0f, 0},
  {554.0f, 0, 50, 0, 0.0f, false, 0, 0.0f, 0.0f, 0},
  {659.0f, 0, 50, 0, 0.0f, false, 0, 0.0f, 0.0f, 0}
};
const float SID_SUSTAIN = 0.62f;
const float SID_ATTACK_RATE = 0.0016f;
const float SID_DECAY_RATE = 0.0006f;
const float SID_RELEASE_RATE = 0.0004f;
// ---- SID engine (lib/sid: 3-voice 6581-style core, ADSR, filter) --------------------------------
#include "sid.h"
static sid_t sid;
static uint8_t sidWaveBits(int w) {
  switch (w) { case 1: return SID_CTRL_SAWTOOTH; case 2: return SID_CTRL_PULSE; case 3: return SID_CTRL_NOISE; default: return SID_CTRL_TRIANGLE; }
}
static void sidSetup() {
  sid_init(&sid, 44100, SID_CLOCK_PAL_HZ);
  for (int v = 0; v < 3; v++) {
    sid_set_adsr(&sid, v, 0, 8, 9, 5);          // fast attack, 300 ms decay to sustain 9/15, ~170 ms release
    sid_set_pulse_width(&sid, v, sidVoices[v].pulseWidth / 100.0f);
    sid_set_control(&sid, v, sidWaveBits(sidVoices[v].waveform));
  }
  sid_set_volume(&sid, 15);
}
void gateVoice(int v, float freq, int durationMs) {
  if (v < 0 || v > 2) return;
  sidVoices[v].freq = freq;
  sidVoices[v].gated = true;
  sidVoices[v].stage = 1;
  sidVoices[v].remaining = (long)44100 * durationMs / 1000;
  lastVoice = v;
  // SID: program the oscillator and open the gate (envelope attack starts)
  sid_set_freq_hz(&sid, v, freq);
  sid_set_pulse_width(&sid, v, sidVoices[v].pulseWidth / 100.0f);
  sid_set_control(&sid, v, sidWaveBits(sidVoices[v].waveform) | SID_CTRL_GATE);
}
void renderVoices() {
  // SID: render until every gate is closed and every envelope has died out (max 3 s)
  int16_t buf[256];
  long guard = (long)44100 * 3;
  while (guard > 0) {
    bool active = false;
    for (int v = 0; v < 3; v++) {
      SidVoice &sv = sidVoices[v];
      if (sv.gated) {
        sv.remaining -= 256;
        if (sv.remaining <= 0) { sv.gated = false; sv.stage = 4; sid_gate(&sid, v, false); }
        active = true;
      } else if (sid.voice[v].envelope != 0) { active = true; } else { sv.stage = 0; }
    }
    if (!active) break;
    sid_render(&sid, buf, 256);
    for (int i = 0; i < 256; i++) buf[i] = (int16_t)(buf[i] / 2);   // headroom; Speaker::writeSamples applies the volume
    speaker_1.writeSamples(buf, 256);
    guard -= 256;
  }
}
void playPulseNote(float freq, int durationMs) {
  gateVoice(0, freq, durationMs);
  renderVoices();
}
void playCurrentNote() {
  int base = NOTE_TABLE[noteIndex];
  int octShift = octave - 4;
  float freq = base * pow(2.0f, octShift);
  if (freq < 80) freq = 80;
  if (freq > 1500) freq = 1500;
  gateVoice(0, freq, 300);
  renderVoices();
}
void drawHeaderUI(const char* title = "POCKET SYNTH") {
  st7735_tft_1.fillRect(0, 0, 160, 22, UI_BG);
  st7735_tft_1.setFont(&FreeSansBold9pt7b);
  st7735_tft_1.setTextColor(UI_ACCENT);
  st7735_tft_1.setCursor(6, 16);
  st7735_tft_1.print(title);
}
// ---- SID tune player (lib/crsid: a whole C64 — 6502 CPU, SID, CIA, VIC) ------------------------
// The synth above drives a SID *chip* model directly. This plays real .sid files, which are 6502
// machine code that writes the SID registers 50 times a second exactly as on a C64, so the tunes
// sound as their composers wrote them. Same engine the esp32-screen panel uses; here it feeds the
// same Speaker the synth does, at the same 44.1 kHz, so no resampling is needed.
extern "C" {
#include "libcRSID.h"
#include "sidtunes.h"
}

#define TUNE_CHUNK 256                 // frames per pump: 5.8 ms of audio, so buttons stay responsive

static cRSID_C64instance* tuneC64 = nullptr;
static bool tunePlaying = false;
static int  tuneIndex = 0, tuneSubtune = 1, tuneSubtunes = 1;
static char tuneTitle[33] = "", tuneAuthor[33] = "";
// Jukebox volume and mute. The volume is the speaker's; mute keeps it and plays at zero, so the
// tune keeps running (and pacing the loop) and comes back where it was.
static float jukeVol = 0.3f;
static bool  jukeMuted = false;
#define JUKE_VOL_STEP 0.05f

// The encoder ring is the volume dial while a tune plays: a pointer from 7 o'clock (silent) round
// to 5 o'clock (full), cyan, or red when muted. Ring positions run counter-clockwise from 12.
static void jukeRing() {
  if (jukeMuted) rotary_encoder_1.setRingColor(255, 40, 0); else rotary_encoder_1.setRingColor(0, 200, 255);
  float sweep = 10.0f;                              // LEDs of travel, leaving the bottom gap
  float pos = 7.0f - sweep * jukeVol;               // 7 o'clock → clockwise (decreasing) → 5 o'clock
  if (pos < 0) pos += 12.0f;
  rotary_encoder_1.setRingPosition(pos);
}
static void jukeApplyVolume() {
  speaker_1.setVolume(jukeMuted ? 0.0f : jukeVol);
  jukeRing();
  needsRedraw = true;
}
static void jukeSetVolume(float v) {
  if (v < 0.0f) v = 0.0f; if (v > 1.0f) v = 1.0f;
  jukeVol = v;
  jukeApplyVolume();
  char txt[8]; snprintf(txt, sizeof(txt), "%d", (int)(jukeVol * 100.0f + 0.5f));
  wifi.postStateEvent("volume", txt);
}
static void jukeSetMute(bool on) {
  jukeMuted = on;
  jukeApplyVolume();
  wifi.postStateEvent("mute", on ? "1" : "0");
  Serial.printf("[sid] %s\n", on ? "muted" : "unmuted");
}

static void tuneField(char* dst, const char* src) {
  memcpy(dst, src, 32);                // PSID header strings are fixed 32-byte fields, often unterminated
  dst[32] = '\0';
}

static bool tuneStart(int idx, int subtune) {
  if (SID_TUNE_COUNT <= 0) return false;
  // The emulated C64 is ~270 KB — most of this board's free heap, and it has no PSRAM. Hold it
  // only while a tune plays, so the synth and the WiFi stack get the memory back afterwards.
  if (!tuneC64) {
    tuneC64 = cRSID_init(44100, TUNE_CHUNK);
    if (!tuneC64) { Serial.printf("[sid] not enough memory for the C64 (free heap %u)\n", (unsigned)ESP.getFreeHeap()); return false; }
    Serial.printf("[sid] C64 ready (free heap %u)\n", (unsigned)ESP.getFreeHeap());
  }
  idx = ((idx % SID_TUNE_COUNT) + SID_TUNE_COUNT) % SID_TUNE_COUNT;      // wrap both ways
  cRSID_SIDheader* h = cRSID_processSIDfile(tuneC64, (unsigned char*)SID_TUNES[idx].data,
                                            (int)SID_TUNES[idx].len);
  if (!h) { Serial.printf("[sid] bad SID file: %s\n", SID_TUNES[idx].name); return false; }
  tuneField(tuneTitle, h->Title);
  tuneField(tuneAuthor, h->Author);
  tuneSubtunes = h->SubtuneAmount ? h->SubtuneAmount : 1;
  if (subtune <= 0) subtune = h->DefaultSubtune ? h->DefaultSubtune : 1;
  if (subtune > tuneSubtunes) subtune = 1;
  cRSID_initSIDtune(tuneC64, h, subtune);
  bool entering = !tunePlaying;
  tuneIndex = idx; tuneSubtune = subtune; tunePlaying = true;
  if (entering) { jukeVol = speaker_1.getVolume(); jukeMuted = false; drawHeaderUI("SID PLAYER"); jukeApplyVolume(); }
  needsRedraw = true;
  Serial.printf("[sid] playing \"%s\" by %s (subtune %d/%d)\n",
                tuneTitle, tuneAuthor, subtune, tuneSubtunes);
  char ev[48]; snprintf(ev, sizeof(ev), "%d/%d %d/%d", tuneIndex + 1, SID_TUNE_COUNT, tuneSubtune, tuneSubtunes);
  wifi.postStateEvent("sid_tune", ev);
  return true;
}

// Next subtune of the current tune, wrapping (a one-subtune file restarts).
static void tuneNextSubtune() {
  if (!tunePlaying) return;
  tuneStart(tuneIndex, tuneSubtune % tuneSubtunes + 1);
}

static void tuneStop() {
  if (!tunePlaying) return;
  tunePlaying = false;
  speaker_1.stop();
  if (jukeMuted) { jukeMuted = false; speaker_1.setVolume(jukeVol); }   // the synth is never muted
  rotary_encoder_1.setRingColor(0, 200, 255);
  rotary_encoder_1.setRingPosition(NAN);                                // ring follows the knob again
  drawHeaderUI();
  needsRedraw = true;
  if (tuneC64) { cRSID_free(); tuneC64 = nullptr; }
  Serial.printf("[sid] stopped (free heap %u)\n", (unsigned)ESP.getFreeHeap());
}

// One chunk per call. Speaker::writeSamples blocks on the I2S DMA, which is what paces playback.
static void tunePump() {
  if (!tuneC64) return;
  static int16_t buf[TUNE_CHUNK];
  cRSID_generateBuffer(tuneC64, buf, TUNE_CHUNK);
  speaker_1.writeSamples(buf, TUNE_CHUNK);
}

void drawNoteUI() {
  st7735_tft_1.fillRect(0, 22, 160, 40, UI_BG);
  st7735_tft_1.setFont(&FreeSansBold18pt7b);
  st7735_tft_1.setTextColor(UI_VALUE);
  st7735_tft_1.setCursor(8, 58);
  st7735_tft_1.print(NOTE_NAMES[noteIndex]);
  st7735_tft_1.print(octave);
}
void drawFooterUI() {
  st7735_tft_1.fillRect(0, 62, 160, 18, UI_BG);
  st7735_tft_1.setFont(&FreeSans9pt7b);
  st7735_tft_1.setTextColor(UI_LABEL);
  st7735_tft_1.setCursor(6, 76);
  st7735_tft_1.print("Wave: ");
  st7735_tft_1.print(WAVE_NAMES[waveform]);
  st7735_tft_1.print("  V");
  st7735_tft_1.print(lastVoice + 1);
}
void drawTuneUI() {
  st7735_tft_1.fillRect(0, 22, 160, 58, UI_BG);
  st7735_tft_1.setFont(&FreeSansBold9pt7b);
  st7735_tft_1.setTextColor(UI_VALUE);
  st7735_tft_1.setCursor(6, 40);
  st7735_tft_1.print(tuneTitle[0] ? tuneTitle : SID_TUNES[tuneIndex].name);
  st7735_tft_1.setFont(&FreeSans9pt7b);
  st7735_tft_1.setTextColor(UI_LABEL);
  st7735_tft_1.setCursor(6, 58);
  st7735_tft_1.print(tuneAuthor);
  st7735_tft_1.setTextColor(UI_ACCENT);
  st7735_tft_1.setCursor(6, 76);
  char pos[24];
  snprintf(pos, sizeof(pos), "%d/%d  sub %d/%d", tuneIndex + 1, SID_TUNE_COUNT, tuneSubtune, tuneSubtunes);
  st7735_tft_1.print(pos);
  // volume: a bar at the right of the footer, or MUTED
  const int bx = 112, by = 66, bw = 42, bh = 8;
  if (jukeMuted) {                       // a red MUTE badge where the bar was, in the built-in 6x8 font
    st7735_tft_1.drawRect(bx, by - 2, bw, bh + 4, ST7735_TFT::COLOR_RED);
    st7735_tft_1.setFont(nullptr);
    st7735_tft_1.setTextColor(ST7735_TFT::COLOR_RED);
    st7735_tft_1.setCursor(bx + 9, by);
    st7735_tft_1.print("MUTE");
    st7735_tft_1.setFont(&FreeSans9pt7b);
  } else {
    st7735_tft_1.drawRect(bx, by, bw, bh, UI_LABEL);
    int fill = (int)((bw - 2) * jukeVol + 0.5f);
    if (fill > 0) st7735_tft_1.fillRect(bx + 1, by + 1, fill, bh - 2, UI_VALUE);
  }
}

void handleMessage(const char* action, const char* value) {
  if (strcmp(action, "play_note") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["frequency"].is<int>() || !d["duration"].is<int>()) return;
    int freq = d["frequency"]; int dur = d["duration"];
    if (freq < 20 || freq > 5000) return;
    if (dur < 0 || dur > 5000) return;
    speaker_1.playNote(freq, dur);
    return;
  }
  if (strcmp(action, "play_tone") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["frequency"].is<int>() || !d["duration"].is<int>()) return;
    int freq = d["frequency"]; int dur = d["duration"];
    if (freq < 20 || freq > 5000) return;
    if (dur < 0 || dur > 5000) return;
    speaker_1.playTone(freq, dur);
    return;
  }
  if (strcmp(action, "play_chord") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["frequencies"].is<JsonArray>() || !d["duration"].is<int>()) return;
    JsonArray arr = d["frequencies"].as<JsonArray>();
    int dur = d["duration"];
    if (dur < 0 || dur > 5000) return;
    float fs[4]; int n = 0;
    for (JsonVariant v : arr) {
      if (n >= 4) break;
      if (!v.is<float>() && !v.is<int>()) continue;
      float f = v.as<float>();
      if (f < 20 || f > 5000) continue;
      fs[n++] = f;
    }
    if (n > 0) speaker_1.playChord(fs, n, dur);
    return;
  }
  if (strcmp(action, "speaker_stop") == 0) {
    speaker_1.stop();
    return;
  }
  if (strcmp(action, "set_volume") == 0) {
    float v = atof(value);
    if (v < 0.0f || v > 1.0f) return;
    if (tunePlaying) jukeSetVolume(v); else speaker_1.setVolume(v);
    return;
  }
  if (strcmp(action, "pin_probe") == 0) {                  // diagnostics: sample a GPIO 2000x over 100 ms, report the lows
    int pin = atoi(value); if (pin < 0 || pin > 48) return;
    int lows = 0, run = 0, longest = 0, runs = 0;
    for (int i = 0; i < 2000; i++) {
      bool low = digitalRead(pin) == LOW;
      if (low) { lows++; if (++run > longest) longest = run; } else { if (run) runs++; run = 0; }
      ets_delay_us(50);
    }
    if (run) runs++;
    Serial.printf("[probe] gpio%d: %d/2000 low, %d low runs, longest %d samples (%d us)\n", pin, lows, runs, longest, longest * 50);
    return;
  }
  if (strcmp(action, "mute") == 0) {                       // "1", "0", or empty = toggle
    if (!tunePlaying) return;
    jukeSetMute(value && *value ? atoi(value) != 0 : !jukeMuted);
    return;
  }
  if (strcmp(action, "sid_subtune") == 0) {                // a number, or empty = next
    if (!tunePlaying) return;
    if (value && *value) tuneStart(tuneIndex, atoi(value)); else tuneNextSubtune();
    return;
  }
  if (strcmp(action, "set_waveform") == 0) {
    JsonDocument d;
    int w = atoi(value);
    int v = 0;
    if (deserializeJson(d, value) == DeserializationError::Ok && d.is<JsonObject>()) {
      if (!d["waveform"].is<int>()) return;
      w = d["waveform"];
      if (d["voice"].is<int>()) v = d["voice"];
    }
    if (w < 0 || w > 3) return;
    if (v < 0 || v > 2) return;
    sidVoices[v].waveform = w;
    if (v == 0) waveform = w;
    sid_set_control(&sid, v, sidWaveBits(w) | (sidVoices[v].gated ? SID_CTRL_GATE : 0));
    lastVoice = v;
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "set_pulse_width") == 0) {
    JsonDocument d;
    int p = atoi(value);
    int v = 0;
    if (deserializeJson(d, value) == DeserializationError::Ok && d.is<JsonObject>()) {
      if (!d["pulse_width"].is<int>()) return;
      p = d["pulse_width"];
      if (d["voice"].is<int>()) v = d["voice"];
    }
    if (p < 0 || p > 100) return;
    if (v < 0 || v > 2) return;
    sidVoices[v].pulseWidth = p;
    if (v == 0) pulseWidth = p;
    sid_set_pulse_width(&sid, v, p / 100.0f);
    lastVoice = v;
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "set_voice_note") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["frequency"].is<int>()) return;
    int f = d["frequency"];
    int v = d["voice"].is<int>() ? (int)d["voice"] : 0;
    int dur = d["duration"].is<int>() ? (int)d["duration"] : 300;
    if (f < 20 || f > 5000) return;
    if (v < 0 || v > 2) return;
    if (dur < 0 || dur > 5000) return;
    gateVoice(v, (float)f, dur);
    renderVoices();
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "play_chord_voices") == 0) {
    int base = NOTE_TABLE[noteIndex];
    float f0 = base * pow(2.0f, octave - 4);
    gateVoice(0, f0, 400);
    gateVoice(1, f0 * 1.25f, 400);
    gateVoice(2, f0 * 1.5f, 400);
    renderVoices();
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "play_sid") == 0) {
    tuneStart(value && *value ? atoi(value) : tuneIndex, 0);
    return;
  }
  if (strcmp(action, "next_sid") == 0) {
    tuneStart(tuneIndex + 1, 0);
    return;
  }
  if (strcmp(action, "stop_sid") == 0) {
    tuneStop();
    return;
  }
  if (strcmp(action, "stop_all_voices") == 0) {
    for (int v = 0; v < 3; v++) {
      sidVoices[v].gated = false;
      sidVoices[v].stage = 0;
      sidVoices[v].env = 0.0f;
      sidVoices[v].smooth = 0.0f;
      sidVoices[v].phase = 0.0f;
      sid_gate(&sid, v, false);
    }
    speaker_1.stop();
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "set_note") == 0) {
    int n = atoi(value);
    if (n < 0 || n > 11) return;
    noteIndex = n;
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "set_octave") == 0) {
    int o = atoi(value);
    if (o < 2 || o > 7) return;
    octave = o;
    needsRedraw = true;
    return;
  }
  if (strcmp(action, "trigger_note") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) == DeserializationError::Ok && d.is<JsonObject>() && d["voice"].is<int>()) {
      int v = d["voice"];
      if (v < 0 || v > 2) return;
      int base = NOTE_TABLE[noteIndex];
      float f = base * pow(2.0f, octave - 4);
      if (d["frequency"].is<int>()) {
        int ff = d["frequency"];
        if (ff < 20 || ff > 5000) return;
        f = (float)ff;
      }
      gateVoice(v, f, 300);
      renderVoices();
      needsRedraw = true;
    } else {
      playCurrentNote();
    }
    wifi.postStateEvent("note_triggered", NOTE_NAMES[noteIndex]);
    return;
  }
  if (strcmp(action, "set_ring_color") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["r"].is<int>() || !d["g"].is<int>() || !d["b"].is<int>()) return;
    int r = d["r"]; int g = d["g"]; int b = d["b"];
    if (r < 0 || r > 255 || g < 0 || g > 255 || b < 0 || b > 255) return;
    rotary_encoder_1.setRingColor(r, g, b);
    return;
  }
  if (strcmp(action, "set_ring_brightness") == 0) {
    int b = atoi(value);
    if (b < 0 || b > 255) return;
    rotary_encoder_1.setRingBrightness(b);
    return;
  }
}

// ========== MAIN TASK (runs on Core 1) ==========
void mainTask(void* parameter) {
  esp_task_wdt_add(NULL);  // Subscribe to task watchdog (30s timeout)
  uint32_t _lastHeapLog = 0;
  // Task runs forever
  while (true) {
    esp_task_wdt_reset();
    uint32_t _nowMs = millis();
    if (_nowMs - _lastHeapLog > 30000) {
      _lastHeapLog = _nowMs;
      Serial.printf("[Atech heap] free=%u min=%u\n", (unsigned)ESP.getFreeHeap(), (unsigned)ESP.getMinFreeHeap());
    }
        // ========== USER BEHAVIOR ==========
        wifi.maintain();
        rotary_encoder_1.update();
        button_1.update();
        button_2.update();

        // ---- The knob is the mode switch: a press starts the SID player from the synth; in the
        // player a press mutes and a 1.5 s hold stops (back to the synth). The buttons act once a
        // press has lasted PRESS_MS, so they never wait for a release.
        //
        // PRESS_MS is the debounce the SDK's button and encoder switch do not have: a press counts
        // once the pin has read pressed for that long. Contact bounce is over in a few ms; nothing a
        // finger does is that short. (The pins themselves are clean — pin_probe measured them.)
        const uint32_t PRESS_MS = 40;
        static uint32_t knobDownMs = 0;
        static bool knobLong = false, knobShort = false;    // knobShort: a real press that ended before the hold time
        knobShort = false;
        if (rotary_encoder_1.isPressed()) {
          if (!knobDownMs) knobDownMs = millis();
          else if (!knobLong && millis() - knobDownMs > 1500) {
            knobLong = true;
            if (tunePlaying) tuneStop(); else tuneStart(tuneIndex, 0);
          }
        } else {
          if (knobDownMs && !knobLong && millis() - knobDownMs >= PRESS_MS) knobShort = true;
          knobDownMs = 0; knobLong = false;
        }
        rotary_encoder_1.wasPressed();                       // the edge is handled above
        // a button "fires" once its press has lasted PRESS_MS; released resets it
        static uint32_t btn1DownMs = 0, btn2DownMs = 0;
        static bool btn1Fired = false, btn2Fired = false;
        auto fired = [&](ButtonModule& b, uint32_t& down, bool& done) -> bool {
          if (b.isPressed()) { if (!down) down = millis(); if (!done && millis() - down >= PRESS_MS) { done = true; return true; } }
          else { down = 0; done = false; }
          return false;
        };
        bool btn1Fire = fired(button_1, btn1DownMs, btn1Fired), btn2Fire = fired(button_2, btn2DownMs, btn2Fired);

        // While a tune plays the board is a SID player, not a synth:
        //   encoder      volume        knob press   mute / unmute       hold knob   stop
        //   button 1     next tune     button 2     next subtune
        // Rendering paces this loop, so nothing else runs here.
        if (tunePlaying) {
          int32_t tpos = rotary_encoder_1.getPosition();
          if (tpos != lastEncoderPos) {
            int32_t delta = tpos - lastEncoderPos;
            lastEncoderPos = tpos;
            jukeSetVolume(jukeVol + JUKE_VOL_STEP * (float)delta);
          }
          if (knobShort) jukeSetMute(!jukeMuted);
          if (btn1Fire) tuneStart(tuneIndex + 1, 0);
          if (btn2Fire) tuneNextSubtune();
          button_1.wasPressed(); button_1.wasReleased(); button_2.wasPressed(); button_2.wasReleased();   // edges handled above
          if (!tunePlaying) continue;                        // stopped just now: let the synth redraw its screen
          if (needsRedraw && (millis() - lastFrameMs >= 30)) {
            lastFrameMs = millis();
            needsRedraw = false;
            drawTuneUI();
            st7735_tft_1.display();
          }
          // tuneStop() above frees the C64, so re-check before rendering: pumping a freed
          // instance is a use-after-free (it crashed the board when the knob stopped playback).
          if (tunePlaying) tunePump();   // blocks on the I2S DMA — that is what paces playback
          else vTaskDelay(pdMS_TO_TICKS(4));
          continue;
        }

        int32_t pos = rotary_encoder_1.getPosition();
        if (pos != lastEncoderPos) {
        int32_t delta = pos - lastEncoderPos;
        lastEncoderPos = pos;
        noteIndex += delta;
        while (noteIndex < 0) { noteIndex += 12; octave--; if (octave < 3) octave = 3; }
        while (noteIndex > 11) { noteIndex -= 12; octave++; if (octave > 6) octave = 6; }
        needsRedraw = true;
        gateVoice(2, NOTE_E5, 40);
        renderVoices();
        wifi.postSensorEventInt("knob_position", pos, "rotary_encoder_knob");
        }

        if (knobShort) {                      // a knob press in the synth starts the SID player
        wifi.postButtonEvent("knob_press", 1);
        if (tuneStart(tuneIndex, 0)) continue;   // the player draws its own screen next round
        }

        if (button_1.wasPressed()) {
        playCurrentNote();
        wifi.postButtonEvent("button_press", 1);
        char noteStr[8];
        snprintf(noteStr, sizeof(noteStr), "%s%d", NOTE_NAMES[noteIndex], octave);
        wifi.postStateEvent("note_triggered", noteStr);
        }
        if (button_1.wasReleased()) {
        wifi.postButtonEvent("button_release", 0);
        }

        if (button_2.wasPressed()) {
        waveform = (waveform + 1) % 4;
        sidVoices[0].waveform = waveform;
        needsRedraw = true;
        wifi.postButtonEvent("button_press", 1);
        wifi.postStateEvent("waveform", WAVE_NAMES[waveform]);
        gateVoice(2, NOTE_A4, 60);
        renderVoices();
        gateVoice(2, NOTE_C5, 80);
        renderVoices();
        }
        if (button_2.wasReleased()) {
        wifi.postButtonEvent("button_release", 0);
        }

        if (needsRedraw && (millis() - lastFrameMs >= 30)) {
        lastFrameMs = millis();
        needsRedraw = false;
        drawNoteUI();
        drawFooterUI();
        st7735_tft_1.display();
        }

        vTaskDelay(pdMS_TO_TICKS(4));
  }
}

// ========== SETUP ==========
void setup() {
  Serial.setRxBufferSize(8192);
  Serial.begin(115200);
  Serial.setTxTimeoutMs(0);
  Serial.println("Initializing...");

  // ========== BOOT DIAGNOSTICS ==========
  {
    Preferences _bootPrefs;
    _bootPrefs.begin("atech_boot", false);
    uint32_t _bootCount = _bootPrefs.getUInt("count", 0) + 1;
    _bootPrefs.putUInt("count", _bootCount);
    _bootPrefs.end();

    esp_reset_reason_t _reason = esp_reset_reason();
    const char* _reasonStr = "UNKNOWN";
    switch (_reason) {
      case ESP_RST_POWERON:   _reasonStr = "POWERON";   break;
      case ESP_RST_EXT:       _reasonStr = "EXT_PIN";   break;
      case ESP_RST_SW:        _reasonStr = "SOFTWARE";  break;
      case ESP_RST_PANIC:     _reasonStr = "PANIC";     break;
      case ESP_RST_INT_WDT:   _reasonStr = "INT_WDT";   break;
      case ESP_RST_TASK_WDT:  _reasonStr = "TASK_WDT";  break;
      case ESP_RST_WDT:       _reasonStr = "OTHER_WDT"; break;
      case ESP_RST_DEEPSLEEP: _reasonStr = "DEEPSLEEP"; break;
      case ESP_RST_BROWNOUT:  _reasonStr = "BROWNOUT";  break;
      case ESP_RST_SDIO:      _reasonStr = "SDIO";      break;
      default: break;
    }

    Serial.println();
    Serial.println("================ ATECH BOOT ================");
    Serial.printf("  Boot count : %u\n", _bootCount);
    Serial.printf("  Reset cause: %s (%d)\n", _reasonStr, (int)_reason);
    Serial.printf("  Free heap  : %u bytes\n", (unsigned)ESP.getFreeHeap());
    Serial.printf("  Min heap   : %u bytes (lowest since boot)\n", (unsigned)ESP.getMinFreeHeap());
    Serial.printf("  CPU freq   : %u MHz\n", (unsigned)ESP.getCpuFreqMHz());
    Serial.println("============================================");
  }

  // Initialize modules
  speaker_1.begin(44100);
  sidSetup();
  Serial.printf("[sid] %d tunes embedded, C64 allocated on demand (free heap %u)\n",
                SID_TUNE_COUNT, (unsigned)ESP.getFreeHeap());
  st7735_tft_1.begin();
  delay(150);  // Allow display to stabilize
  rotary_encoder_1.begin();
  button_1.begin();
  button_2.begin();

  // ========== USB-SERIAL TRANSPORT ==========
  wifi.connect();  // Serial.begin(115200) — always succeeds
  Serial.println("[Atech] Transport: USB-Serial");

  Serial.println("Setup complete!");

  // ========== USER BEHAVIOR SETUP ==========
  speaker_1.setVolume(0.3f);
  rotary_encoder_1.setAcceleration(true, 4);
  rotary_encoder_1.setRingColor(0, 200, 255);
  rotary_encoder_1.setRingBrightness(80);
  lastEncoderPos = rotary_encoder_1.getPosition();

  st7735_tft_1.clear();
  st7735_tft_1.fillScreen(UI_BG);
  drawHeaderUI();
  drawNoteUI();
  drawFooterUI();
  st7735_tft_1.display();

  wifi.onMessage(handleMessage);

  // ========== TASK WATCHDOG ==========
  esp_task_wdt_init(30, true);  // 30s timeout, panic on trigger

  // ========== CREATE FREERTOS TASKS ==========
  // Create main task on Core 1 (Core 0 is used by WiFi/BT)
  xTaskCreatePinnedToCore(
    mainTask,           // Task function
    "MainTask",         // Task name
    16384,              // Stack size (bytes) - 16KB for HTTPS/TLS
    NULL,               // Parameters
    1,                  // Priority (1 = low, higher = more priority)
    &mainTaskHandle,    // Task handle
    1                   // Core ID (0 or 1)
  );

  Serial.println("FreeRTOS tasks started!");
}

// ========== MAIN LOOP (empty - tasks handle everything) ==========
void loop() {
  // Nothing here - FreeRTOS tasks handle all operations
  // This allows other tasks and system processes to run
  vTaskDelay(portMAX_DELAY);
}
